#!/usr/bin/env ruby

require "bundler/setup"
require 'goodboy'

begin
  puts Goodboy.run(*ARGV)
  Goodboy.debug { puts "no exception, exerything is allright" }
  exit 0
rescue => error
  STDERR.puts error.message
  Goodboy.debug { STDERR.puts error.backtrace }
  exit 1
end

